language: ruby

rvm:
  - 1.9.3

env:
  AUDIODEV=null

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev timidity libsdl-ttf2.0-dev libsdl-sge-dev fonts-horai-umefont fonts-ipafont
